# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_dialog.ui'
#
# Created: Fri Apr 17 20:40:11 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(468, 675)
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 417, 393))
        self.tabWidget.setStatusTip(_fromUtf8(""))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.continent_1 = QtGui.QWidget()
        self.continent_1.setObjectName(_fromUtf8("continent_1"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.continent_1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.toolBox = QtGui.QToolBox(self.continent_1)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.currency_1 = QtGui.QWidget()
        self.currency_1.setGeometry(QtCore.QRect(0, 0, 81, 249))
        self.currency_1.setObjectName(_fromUtf8("currency_1"))
        self.toolBox.addItem(self.currency_1, _fromUtf8(""))
        self.currency_2 = QtGui.QWidget()
        self.currency_2.setGeometry(QtCore.QRect(0, 0, 81, 249))
        self.currency_2.setObjectName(_fromUtf8("currency_2"))
        self.toolBox.addItem(self.currency_2, _fromUtf8(""))
        self.currency_3 = QtGui.QWidget()
        self.currency_3.setGeometry(QtCore.QRect(0, 0, 81, 249))
        self.currency_3.setObjectName(_fromUtf8("currency_3"))
        self.toolBox.addItem(self.currency_3, _fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.toolBox)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.rate_1 = QtGui.QPushButton(self.continent_1)
        self.rate_1.setObjectName(_fromUtf8("rate_1"))
        self.gridLayout.addWidget(self.rate_1, 0, 0, 1, 1)
        self.rate_2 = QtGui.QPushButton(self.continent_1)
        self.rate_2.setObjectName(_fromUtf8("rate_2"))
        self.gridLayout.addWidget(self.rate_2, 0, 1, 1, 1)
        self.rate_3 = QtGui.QPushButton(self.continent_1)
        self.rate_3.setObjectName(_fromUtf8("rate_3"))
        self.gridLayout.addWidget(self.rate_3, 0, 2, 1, 1)
        self.rate_4 = QtGui.QPushButton(self.continent_1)
        self.rate_4.setObjectName(_fromUtf8("rate_4"))
        self.gridLayout.addWidget(self.rate_4, 1, 0, 1, 1)
        self.rate_5 = QtGui.QPushButton(self.continent_1)
        self.rate_5.setObjectName(_fromUtf8("rate_5"))
        self.gridLayout.addWidget(self.rate_5, 1, 1, 1, 1)
        self.rate_6 = QtGui.QPushButton(self.continent_1)
        self.rate_6.setObjectName(_fromUtf8("rate_6"))
        self.gridLayout.addWidget(self.rate_6, 1, 2, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.continent_1, _fromUtf8(""))
        self.continent_2 = QtGui.QWidget()
        self.continent_2.setObjectName(_fromUtf8("continent_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.continent_2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.toolBox_2 = QtGui.QToolBox(self.continent_2)
        self.toolBox_2.setObjectName(_fromUtf8("toolBox_2"))
        self.currency_4 = QtGui.QWidget()
        self.currency_4.setGeometry(QtCore.QRect(0, 0, 73, 278))
        self.currency_4.setObjectName(_fromUtf8("currency_4"))
        self.toolBox_2.addItem(self.currency_4, _fromUtf8(""))
        self.currency_5 = QtGui.QWidget()
        self.currency_5.setGeometry(QtCore.QRect(0, 0, 73, 278))
        self.currency_5.setObjectName(_fromUtf8("currency_5"))
        self.toolBox_2.addItem(self.currency_5, _fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.toolBox_2)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.zone_1 = QtGui.QLabel(self.continent_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.zone_1.setFont(font)
        self.zone_1.setTextFormat(QtCore.Qt.AutoText)
        self.zone_1.setAlignment(QtCore.Qt.AlignCenter)
        self.zone_1.setObjectName(_fromUtf8("zone_1"))
        self.verticalLayout_2.addWidget(self.zone_1)
        self.rate_10 = QtGui.QPushButton(self.continent_2)
        self.rate_10.setToolTip(_fromUtf8(""))
        self.rate_10.setStatusTip(_fromUtf8(""))
        self.rate_10.setWhatsThis(_fromUtf8(""))
        self.rate_10.setObjectName(_fromUtf8("rate_10"))
        self.verticalLayout_2.addWidget(self.rate_10)
        self.rate_11 = QtGui.QPushButton(self.continent_2)
        self.rate_11.setObjectName(_fromUtf8("rate_11"))
        self.verticalLayout_2.addWidget(self.rate_11)
        self.rate_12 = QtGui.QPushButton(self.continent_2)
        self.rate_12.setObjectName(_fromUtf8("rate_12"))
        self.verticalLayout_2.addWidget(self.rate_12)
        self.rate_13 = QtGui.QPushButton(self.continent_2)
        self.rate_13.setObjectName(_fromUtf8("rate_13"))
        self.verticalLayout_2.addWidget(self.rate_13)
        self.rate_14 = QtGui.QPushButton(self.continent_2)
        self.rate_14.setObjectName(_fromUtf8("rate_14"))
        self.verticalLayout_2.addWidget(self.rate_14)
        self.rate_18 = QtGui.QPushButton(self.continent_2)
        self.rate_18.setObjectName(_fromUtf8("rate_18"))
        self.verticalLayout_2.addWidget(self.rate_18)
        self.zone_2 = QtGui.QLabel(self.continent_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.zone_2.setFont(font)
        self.zone_2.setAlignment(QtCore.Qt.AlignCenter)
        self.zone_2.setObjectName(_fromUtf8("zone_2"))
        self.verticalLayout_2.addWidget(self.zone_2)
        self.rate_15 = QtGui.QPushButton(self.continent_2)
        self.rate_15.setObjectName(_fromUtf8("rate_15"))
        self.verticalLayout_2.addWidget(self.rate_15)
        self.rate_16 = QtGui.QPushButton(self.continent_2)
        self.rate_16.setObjectName(_fromUtf8("rate_16"))
        self.verticalLayout_2.addWidget(self.rate_16)
        self.rate_17 = QtGui.QPushButton(self.continent_2)
        self.rate_17.setObjectName(_fromUtf8("rate_17"))
        self.verticalLayout_2.addWidget(self.rate_17)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.zone_3 = QtGui.QLabel(self.continent_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.zone_3.setFont(font)
        self.zone_3.setTextFormat(QtCore.Qt.AutoText)
        self.zone_3.setAlignment(QtCore.Qt.AlignCenter)
        self.zone_3.setObjectName(_fromUtf8("zone_3"))
        self.verticalLayout_3.addWidget(self.zone_3)
        self.rate_19 = QtGui.QPushButton(self.continent_2)
        self.rate_19.setToolTip(_fromUtf8(""))
        self.rate_19.setStatusTip(_fromUtf8(""))
        self.rate_19.setWhatsThis(_fromUtf8(""))
        self.rate_19.setObjectName(_fromUtf8("rate_19"))
        self.verticalLayout_3.addWidget(self.rate_19)
        self.rate_20 = QtGui.QPushButton(self.continent_2)
        self.rate_20.setObjectName(_fromUtf8("rate_20"))
        self.verticalLayout_3.addWidget(self.rate_20)
        self.rate_21 = QtGui.QPushButton(self.continent_2)
        self.rate_21.setObjectName(_fromUtf8("rate_21"))
        self.verticalLayout_3.addWidget(self.rate_21)
        self.rate_22 = QtGui.QPushButton(self.continent_2)
        self.rate_22.setObjectName(_fromUtf8("rate_22"))
        self.verticalLayout_3.addWidget(self.rate_22)
        self.rate_23 = QtGui.QPushButton(self.continent_2)
        self.rate_23.setObjectName(_fromUtf8("rate_23"))
        self.verticalLayout_3.addWidget(self.rate_23)
        self.rate_24 = QtGui.QPushButton(self.continent_2)
        self.rate_24.setObjectName(_fromUtf8("rate_24"))
        self.verticalLayout_3.addWidget(self.rate_24)
        self.zone_4 = QtGui.QLabel(self.continent_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.zone_4.setFont(font)
        self.zone_4.setAlignment(QtCore.Qt.AlignCenter)
        self.zone_4.setObjectName(_fromUtf8("zone_4"))
        self.verticalLayout_3.addWidget(self.zone_4)
        self.rate_25 = QtGui.QPushButton(self.continent_2)
        self.rate_25.setObjectName(_fromUtf8("rate_25"))
        self.verticalLayout_3.addWidget(self.rate_25)
        self.rate_26 = QtGui.QPushButton(self.continent_2)
        self.rate_26.setObjectName(_fromUtf8("rate_26"))
        self.verticalLayout_3.addWidget(self.rate_26)
        self.rate_27 = QtGui.QPushButton(self.continent_2)
        self.rate_27.setObjectName(_fromUtf8("rate_27"))
        self.verticalLayout_3.addWidget(self.rate_27)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.zone_5 = QtGui.QLabel(self.continent_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.zone_5.setFont(font)
        self.zone_5.setTextFormat(QtCore.Qt.AutoText)
        self.zone_5.setAlignment(QtCore.Qt.AlignCenter)
        self.zone_5.setObjectName(_fromUtf8("zone_5"))
        self.verticalLayout_4.addWidget(self.zone_5)
        self.rate_28 = QtGui.QPushButton(self.continent_2)
        self.rate_28.setToolTip(_fromUtf8(""))
        self.rate_28.setStatusTip(_fromUtf8(""))
        self.rate_28.setWhatsThis(_fromUtf8(""))
        self.rate_28.setObjectName(_fromUtf8("rate_28"))
        self.verticalLayout_4.addWidget(self.rate_28)
        self.rate_29 = QtGui.QPushButton(self.continent_2)
        self.rate_29.setObjectName(_fromUtf8("rate_29"))
        self.verticalLayout_4.addWidget(self.rate_29)
        self.rate_30 = QtGui.QPushButton(self.continent_2)
        self.rate_30.setObjectName(_fromUtf8("rate_30"))
        self.verticalLayout_4.addWidget(self.rate_30)
        self.rate_31 = QtGui.QPushButton(self.continent_2)
        self.rate_31.setObjectName(_fromUtf8("rate_31"))
        self.verticalLayout_4.addWidget(self.rate_31)
        self.rate_32 = QtGui.QPushButton(self.continent_2)
        self.rate_32.setObjectName(_fromUtf8("rate_32"))
        self.verticalLayout_4.addWidget(self.rate_32)
        self.rate_33 = QtGui.QPushButton(self.continent_2)
        self.rate_33.setObjectName(_fromUtf8("rate_33"))
        self.verticalLayout_4.addWidget(self.rate_33)
        self.zone_6 = QtGui.QLabel(self.continent_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.zone_6.setFont(font)
        self.zone_6.setAlignment(QtCore.Qt.AlignCenter)
        self.zone_6.setObjectName(_fromUtf8("zone_6"))
        self.verticalLayout_4.addWidget(self.zone_6)
        self.rate_34 = QtGui.QPushButton(self.continent_2)
        self.rate_34.setObjectName(_fromUtf8("rate_34"))
        self.verticalLayout_4.addWidget(self.rate_34)
        self.rate_35 = QtGui.QPushButton(self.continent_2)
        self.rate_35.setObjectName(_fromUtf8("rate_35"))
        self.verticalLayout_4.addWidget(self.rate_35)
        self.rate_36 = QtGui.QPushButton(self.continent_2)
        self.rate_36.setObjectName(_fromUtf8("rate_36"))
        self.verticalLayout_4.addWidget(self.rate_36)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.horizontalLayout.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.continent_2, _fromUtf8(""))

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(2)
        self.toolBox_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.currency_1), _translate("Form", "Page 1", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.currency_2), _translate("Form", "Page 2", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.currency_3), _translate("Form", "Page 3", None))
        self.rate_1.setText(_translate("Form", "PushButton", None))
        self.rate_2.setText(_translate("Form", "PushButton", None))
        self.rate_3.setText(_translate("Form", "PushButton", None))
        self.rate_4.setText(_translate("Form", "PushButton", None))
        self.rate_5.setText(_translate("Form", "PushButton", None))
        self.rate_6.setText(_translate("Form", "PushButton", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.continent_1), "Duke")
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.currency_4), _translate("Form", "Page 1", None))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.currency_5), _translate("Form", "Page 2", None))
        self.zone_1.setText(_translate("Form", "America", None))
        self.rate_10.setText(_translate("Form", "USD/EUR", None))
        self.rate_11.setText(_translate("Form", "PushButton", None))
        self.rate_12.setText(_translate("Form", "PushButton", None))
        self.rate_13.setText(_translate("Form", "PushButton", None))
        self.rate_14.setText(_translate("Form", "PushButton", None))
        self.rate_18.setText(_translate("Form", "PushButton", None))
        self.zone_2.setText(_translate("Form", "Asia", None))
        self.rate_15.setText(_translate("Form", "PushButton", None))
        self.rate_16.setText(_translate("Form", "PushButton", None))
        self.rate_17.setText(_translate("Form", "PushButton", None))
        self.zone_3.setText(_translate("Form", "Caribbean", None))
        self.rate_19.setText(_translate("Form", "USD/EUR", None))
        self.rate_20.setText(_translate("Form", "PushButton", None))
        self.rate_21.setText(_translate("Form", "PushButton", None))
        self.rate_22.setText(_translate("Form", "PushButton", None))
        self.rate_23.setText(_translate("Form", "PushButton", None))
        self.rate_24.setText(_translate("Form", "PushButton", None))
        self.zone_4.setText(_translate("Form", "Europe", None))
        self.rate_25.setText(_translate("Form", "PushButton", None))
        self.rate_26.setText(_translate("Form", "PushButton", None))
        self.rate_27.setText(_translate("Form", "PushButton", None))
        self.zone_5.setText(_translate("Form", "Middle East", None))
        self.rate_28.setText(_translate("Form", "USD/EUR", None))
        self.rate_29.setText(_translate("Form", "PushButton", None))
        self.rate_30.setText(_translate("Form", "PushButton", None))
        self.rate_31.setText(_translate("Form", "PushButton", None))
        self.rate_32.setText(_translate("Form", "PushButton", None))
        self.rate_33.setText(_translate("Form", "PushButton", None))
        self.zone_6.setText(_translate("Form", "Pacific", None))
        self.rate_34.setText(_translate("Form", "PushButton", None))
        self.rate_35.setText(_translate("Form", "PushButton", None))
        self.rate_36.setText(_translate("Form", "PushButton", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.continent_2), _translate("Form", "Tab 2", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

